stages:
  ensemble_10km_test:
    cmd: wavi ensemble_10km_test ingest datasets
    deps:
    - datasets/ensemble_10km_test.nc
    - wavi_on_ray/ensemble_10km_test/ingestion.py
    outs:
    - datasets/prepared/ensemble_10km_test
